-- READING PAL v96.0 - GitHub Pages + Supabase
-- Run this entire script once in Supabase Dashboard > SQL Editor.

create table if not exists public.reading_pal_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null,
  role text not null default 'teacher' check (role in ('teacher','admin')),
  class_data jsonb not null default '{}'::jsonb,
  teacher_name text not null default '',
  school_name text not null default '',
  grade integer not null default 0,
  section text not null default '',
  learners_count integer not null default 0,
  records_count integer not null default 0,
  last_seen timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists reading_pal_profiles_username_lower_uq
on public.reading_pal_profiles (lower(username));

create table if not exists public.reading_pal_feedback (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  username text not null default '',
  category text not null default 'Other',
  message text not null,
  contact text not null default '',
  created_at timestamptz not null default now()
);

alter table public.reading_pal_profiles enable row level security;
alter table public.reading_pal_feedback enable row level security;

create or replace function public.reading_pal_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.reading_pal_profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

revoke all on function public.reading_pal_is_admin() from public;
grant execute on function public.reading_pal_is_admin() to authenticated;

revoke all on table public.reading_pal_profiles from anon, authenticated;
revoke all on table public.reading_pal_feedback from anon, authenticated;

grant select on table public.reading_pal_profiles to authenticated;

grant insert (
  id, username, class_data, teacher_name, school_name, grade, section,
  learners_count, records_count, last_seen, updated_at
) on public.reading_pal_profiles to authenticated;

grant update (
  class_data, teacher_name, school_name, grade, section,
  learners_count, records_count, last_seen, updated_at
) on public.reading_pal_profiles to authenticated;

grant insert (user_id, username, category, message, contact)
on public.reading_pal_feedback to authenticated;

grant select on public.reading_pal_feedback to authenticated;
grant usage, select on sequence public.reading_pal_feedback_id_seq to authenticated;

drop policy if exists "rp profile own read" on public.reading_pal_profiles;
drop policy if exists "rp profile admin read" on public.reading_pal_profiles;
drop policy if exists "rp profile own insert" on public.reading_pal_profiles;
drop policy if exists "rp profile own update" on public.reading_pal_profiles;
drop policy if exists "rp profile admin update" on public.reading_pal_profiles;
drop policy if exists "rp feedback own insert" on public.reading_pal_feedback;
drop policy if exists "rp feedback admin read" on public.reading_pal_feedback;

create policy "rp profile own read"
on public.reading_pal_profiles for select
to authenticated
using (auth.uid() = id);

create policy "rp profile admin read"
on public.reading_pal_profiles for select
to authenticated
using (public.reading_pal_is_admin());

create policy "rp profile own insert"
on public.reading_pal_profiles for insert
to authenticated
with check (auth.uid() = id and role = 'teacher');

create policy "rp profile own update"
on public.reading_pal_profiles for update
to authenticated
using (auth.uid() = id and role = 'teacher')
with check (auth.uid() = id and role = 'teacher');

create policy "rp profile admin update"
on public.reading_pal_profiles for update
to authenticated
using (public.reading_pal_is_admin())
with check (public.reading_pal_is_admin());

create policy "rp feedback own insert"
on public.reading_pal_feedback for insert
to authenticated
with check (auth.uid() = user_id);

create policy "rp feedback admin read"
on public.reading_pal_feedback for select
to authenticated
using (public.reading_pal_is_admin());

-- AFTER creating your intended admin account normally in Reading PAL,
-- promote it by running this separately and replacing the username:
--
-- update public.reading_pal_profiles
-- set role = 'admin'
-- where lower(username) = lower('YOUR_ADMIN_USERNAME');
--
-- Never put an admin password, service-role key, or Supabase secret key in SQL or index.html.
